[package]
name = "trustjectory"
version = "0.1.0"
edition = "2024"

[dependencies]
env = "1.0.1"
futures = "0.3.31"
gamepad = "0.1.6"
nalgebra = "0.34.1"
r2r = "0.9.5"
serde = "1.0.228"
serde_json = "1.0.145"
